module.exports = {
  apps: [
    {
      name: "collector1",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5001,
        PROXY_HOST: "104.43.230.151",
        PROXY_PORT: "3128",
        HTTPS_PROXY: "http://104.43.230.151:3128",
      },
    },
    {
      name: "collector2",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5002,
        PROXY_HOST: "104.43.230.151",
        PROXY_PORT: "3128",
        HTTPS_PROXY: "http://104.43.230.151:3128",
      },
    },
    {
      name: "collector3",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5003,
        PROXY_HOST: "104.43.230.151",
        PROXY_PORT: "3128",
        HTTPS_PROXY: "http://104.43.230.151:3128",
      },
    },
    {
      name: "collector4",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5004,
        PROXY_HOST: "104.43.230.151",
        PROXY_PORT: "3128",
        HTTPS_PROXY: "http://104.43.230.151:3128",
      },
    },
    {
      name: "collector5",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5005,
        PROXY_HOST: "104.43.230.151",
        PROXY_PORT: "3128",
        HTTPS_PROXY: "http://104.43.230.151:3128",
      },
    },
    {
      name: "collector6",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5006,
        PROXY_HOST: "13.95.173.197",
        PROXY_PORT: "80",
        HTTPS_PROXY: "http://13.95.173.197:80",
      },
    },
    {
      name: "collector7",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5007,
        PROXY_HOST: "13.95.173.197",
        PROXY_PORT: "80",
        HTTPS_PROXY: "http://13.95.173.197:80",
      },
    },
    {
      name: "collector8",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5008,
        PROXY_HOST: "13.95.173.197",
        PROXY_PORT: "80",
        HTTPS_PROXY: "http://13.95.173.197:80",
      },
    },
    {
      name: "collector9",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5009,
        PROXY_HOST: "13.95.173.197",
        PROXY_PORT: "80",
        HTTPS_PROXY: "http://13.95.173.197:80",
      },
    },
    {
      name: "collector10",
      script: "build/index.js",
      watch: false,
      autorestart: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5010,
        PROXY_HOST: "13.95.173.197",
        PROXY_PORT: "80",
        HTTPS_PROXY: "http://13.95.173.197:80",
      },
    },
  ],
};
