name: App install and start
#
concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Stop old server (ignore error)
        run: |
          killall -9 node || true

      - name: Remove old server in ~/soruce (ignore error)
        run: |
          rm -rf ~/source || true

      - name: Copy new server to ~/soruce
        run: |
          mkdir -p ~/source
          cp -R ./ ~/source

      - name: Run new server (in background)
        env:
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
          AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
          HOST: ${{ secrets.HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}
          ALIGO_API_KEY: ${{ secrets.ALIGO_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
        run: |
          cd ~/source
          nohup npm run dev </dev/null >/dev/null 2>&1 &
